// GENERATED by endevir - DO NOT EDIT
// ignore_for_file: type=lint

import 'home_test.dart' as home_test;
import 'screens_test.dart' as screens_test;

/// 全テストファイルの登録（endevirTest呼び出し）をまとめて実行する。
void registerAllTests() {
  home_test.main();
  screens_test.main();
}
