#!/usr/bin/env bash
# trace/証跡スキーマ（schema/）からDart/TypeScriptの型を生成する（RPT-006）。
# スキーマが単一の真実。生成物は手で編集しない。
set -euo pipefail
cd "$(dirname "$0")/.."

SCHEMA=schema/trace_event.schema.json
DART_OUT=packages/endevir_reporter/lib/src/generated/trace_event.g.dart
TS_OUT=schema/generated/typescript/trace_event.ts

mkdir -p "$(dirname "$DART_OUT")" "$(dirname "$TS_OUT")"

pnpm exec quicktype --src-lang schema --src "$SCHEMA" --lang dart --top-level TraceEvent -o "$DART_OUT.tmp"
{
  echo "// GENERATED by scripts/codegen.sh from $SCHEMA - DO NOT EDIT"
  echo "// ignore_for_file: type=lint"
  cat "$DART_OUT.tmp"
} > "$DART_OUT"
rm "$DART_OUT.tmp"

pnpm exec quicktype --src-lang schema --src "$SCHEMA" --lang typescript --top-level TraceEvent -o "$TS_OUT.tmp"
{
  echo "// GENERATED by scripts/codegen.sh from $SCHEMA - DO NOT EDIT"
  cat "$TS_OUT.tmp"
} > "$TS_OUT"
rm "$TS_OUT.tmp"

echo "codegen done: $DART_OUT, $TS_OUT"
