// ビルド時テスト列挙とバンドル生成（CORE-104/110、ADR-005）。
// 構文解析のみ（意味解析なし）で高速に endevirTest/endevirGroup を抽出する。
// 実行時ドライラン（Patrol方式）は行わない。
import 'dart:io';

import 'package:analyzer/dart/analysis/features.dart';
import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/visitor.dart';

/// 列挙結果。
class EnumerationResult {
  const EnumerationResult({
    required this.testDir,
    required this.files,
    required this.entries,
    required this.warnings,
  });

  final String testDir;

  /// 列挙対象になったテストファイル（testDirからの相対パス、ソート済み）。
  final List<String> files;

  /// 静的に解決できたテスト。
  final List<EnumeratedTest> entries;

  /// 静的に解決できないテスト名の警告（ADR-005の規約違反）。
  final List<String> warnings;
}

class EnumeratedTest {
  const EnumeratedTest({required this.file, required this.fullName});

  final String file;
  final String fullName;
}

/// [testDir]配下の `*_test.dart`（main_test.dart / *.g.dart を除く）を
/// 静的解析してテストを列挙する。
EnumerationResult enumerateTests(String testDir) {
  final dir = Directory(testDir);
  final files = dir
      .listSync(recursive: true)
      .whereType<File>()
      .map((f) => f.path.substring(dir.path.length + 1))
      .where((p) =>
          p.endsWith('_test.dart') &&
          !p.endsWith('.g.dart') &&
          p != 'main_test.dart')
      .toList()
    ..sort();

  final entries = <EnumeratedTest>[];
  final warnings = <String>[];
  for (final relative in files) {
    final visitor = _TestVisitor(relative);
    final result = parseString(
      content: File('${dir.path}/$relative').readAsStringSync(),
      featureSet: FeatureSet.latestLanguageVersion(),
      throwIfDiagnostics: false,
    );
    result.unit.visitChildren(visitor);
    entries.addAll(visitor.entries);
    warnings.addAll(visitor.warnings);
  }

  return EnumerationResult(
    testDir: testDir,
    files: files,
    entries: entries,
    warnings: warnings,
  );
}

/// 全テストファイルの登録をまとめる `test_bundle.g.dart` の中身を生成する。
String generateBundle(EnumerationResult result) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by endevir - DO NOT EDIT')
    ..writeln('// ignore_for_file: type=lint')
    ..writeln();

  final aliases = <String>[];
  for (final file in result.files) {
    final alias = file
        .replaceAll('.dart', '')
        .replaceAll(RegExp(r'[/\-]'), '_');
    aliases.add(alias);
    buffer.writeln("import '$file' as $alias;");
  }

  buffer
    ..writeln()
    ..writeln('/// 全テストファイルの登録（endevirTest呼び出し）をまとめて実行する。')
    ..writeln('void registerAllTests() {');
  for (final alias in aliases) {
    buffer.writeln('  $alias.main();');
  }
  buffer.writeln('}');
  return buffer.toString();
}

class _TestVisitor extends RecursiveAstVisitor<void> {
  _TestVisitor(this.file);

  final String file;
  final entries = <EnumeratedTest>[];
  final warnings = <String>[];
  final _groupStack = <String>[];
  final _constStrings = <String, String>{};

  @override
  void visitTopLevelVariableDeclaration(TopLevelVariableDeclaration node) {
    for (final variable in node.variables.variables) {
      final initializer = variable.initializer;
      if (initializer is StringLiteral && initializer.stringValue != null) {
        _constStrings[variable.name.lexeme] = initializer.stringValue!;
      }
    }
    super.visitTopLevelVariableDeclaration(node);
  }

  @override
  void visitMethodInvocation(MethodInvocation node) {
    final method = node.methodName.name;
    if (method == 'endevirGroup') {
      final label = _resolveString(node.argumentList.arguments.first);
      _groupStack.add(label ?? '<dynamic group>');
      node.argumentList.accept(this);
      _groupStack.removeLast();
      return;
    }
    if (method == 'endevirTest') {
      final name = _resolveString(node.argumentList.arguments.first);
      final inLoop = node.thisOrAncestorMatching((n) =>
              n is ForStatement || n is WhileStatement || n is DoStatement) !=
          null;
      if (name == null || inLoop) {
        warnings.add('$file: テスト名を静的に解決できません'
            '（${name == null ? "リテラルでない名前" : "ループ内での宣言"}）。'
            'ADR-005の規約に従い、静的な名前で宣言してください');
      } else {
        entries.add(EnumeratedTest(
          file: file,
          fullName: [..._groupStack, name].join(' > '),
        ));
      }
      return;
    }
    super.visitMethodInvocation(node);
  }

  String? _resolveString(Expression expression) {
    if (expression is SimpleStringLiteral) return expression.value;
    if (expression is AdjacentStrings) {
      final parts = expression.strings.map(_resolveString).toList();
      return parts.contains(null) ? null : parts.join();
    }
    if (expression is StringInterpolation) {
      final buffer = StringBuffer();
      for (final element in expression.elements) {
        if (element is InterpolationString) {
          buffer.write(element.value);
        } else if (element is InterpolationExpression) {
          final inner = element.expression;
          if (inner is SimpleIdentifier &&
              _constStrings.containsKey(inner.name)) {
            buffer.write(_constStrings[inner.name]);
          } else {
            return null;
          }
        }
      }
      return buffer.toString();
    }
    if (expression is SimpleIdentifier &&
        _constStrings.containsKey(expression.name)) {
      return _constStrings[expression.name];
    }
    return null;
  }
}
