// `endevir init`: プロジェクトへのEndevir導入（CLI-001）。
// 雛形生成は冪等（既存ファイルを上書きしない）。
// ignore_for_file: avoid_print
import 'dart:convert';
import 'dart:io';

import 'package:args/args.dart';

import 'enumerate.dart';
import 'flutter_cli.dart';

typedef InitProcessRunner = Future<ProcessResult> Function(
  String executable,
  List<String> arguments, {
  String? workingDirectory,
});

class InitResult {
  const InitResult({
    required this.exitCode,
    required this.created,
    this.rolledBack = false,
    this.error,
  });

  final int exitCode;
  final List<String> created;
  final bool rolledBack;
  final String? error;
}

enum EndevirDependencySource { hosted, path, git }

class EndevirDependencyPlan {
  const EndevirDependencyPlan({
    required this.source,
    required this.specs,
    required this.description,
  });

  final EndevirDependencySource source;
  final List<String> specs;
  final String description;
}

EndevirDependencyPlan buildDependencyPlan({
  String? path,
  String? git,
  String? ref,
}) {
  if (path != null && git != null) {
    throw ArgumentError('`--endevir-path` and `--endevir-git` are exclusive');
  }
  if (ref != null && git == null) {
    throw ArgumentError('`--endevir-ref` requires `--endevir-git`');
  }
  if (path != null) {
    final root = Directory(path).absolute.path;
    String descriptor(String package) => jsonEncode({
          'path': '$root/packages/$package',
        });
    return EndevirDependencyPlan(
      source: EndevirDependencySource.path,
      specs: [
        'endevir:${descriptor('endevir')}',
        'dev:endevir_cli:${descriptor('endevir_cli')}',
        'override:endevir_reporter:${descriptor('endevir_reporter')}',
      ],
      description: 'local path ($root)',
    );
  }
  if (git != null) {
    String descriptor(String package) => jsonEncode({
          'git': {
            'url': git,
            'path': 'packages/$package',
            'ref': ?ref,
          },
        });
    return EndevirDependencyPlan(
      source: EndevirDependencySource.git,
      specs: [
        'endevir:${descriptor('endevir')}',
        'dev:endevir_cli:${descriptor('endevir_cli')}',
        'override:endevir_reporter:${descriptor('endevir_reporter')}',
      ],
      description: 'git ($git${ref == null ? '' : ', ref: $ref'})',
    );
  }
  return const EndevirDependencyPlan(
    source: EndevirDependencySource.hosted,
    specs: ['endevir', 'dev:endevir_cli'],
    description: 'pub.dev',
  );
}

const _transactionFiles = [
  'pubspec.yaml',
  'pubspec.lock',
  '.flutter-plugins-dependencies',
  '.dart_tool/package_config.json',
  '.dart_tool/package_graph.json',
  'endevir_test/main_test.dart',
  'endevir_test/app_smoke_test.dart',
  'endevir_test/test_bundle.g.dart',
  'endevir.yaml',
];

class _InitTransaction {
  _InitTransaction(this.projectRoot) {
    for (final path in _transactionFiles) {
      final file = File('$projectRoot/$path');
      _originalFiles[path] = file.existsSync() ? file.readAsBytesSync() : null;
    }
    for (final path in ['endevir_test', '.dart_tool']) {
      _originalDirectories[path] = Directory('$projectRoot/$path').existsSync();
    }
  }

  final String projectRoot;
  final Map<String, List<int>?> _originalFiles = {};
  final Map<String, bool> _originalDirectories = {};

  void rollback() {
    for (final entry in _originalFiles.entries) {
      final file = File('$projectRoot/${entry.key}');
      final original = entry.value;
      if (original == null) {
        if (file.existsSync()) file.deleteSync();
      } else {
        file
          ..createSync(recursive: true)
          ..writeAsBytesSync(original, flush: true);
      }
    }

    // These directories contain only files generated by init/pub when they
    // did not exist before the transaction. Removing them also avoids empty
    // directories after rollback.
    for (final entry in _originalDirectories.entries) {
      if (entry.value) continue;
      final directory = Directory('$projectRoot/${entry.key}');
      if (directory.existsSync()) directory.deleteSync(recursive: true);
    }
  }
}

/// 雛形（endevir_test/main_test.dart, endevir.yaml）を生成する。
/// 生成したファイルの相対パス一覧を返す（既存はスキップ）。
List<String> scaffoldProject(String projectRoot) {
  final pubspec = File('$projectRoot/pubspec.yaml');
  if (!pubspec.existsSync()) {
    throw StateError(
        'pubspec.yamlが見つかりません。Flutterプロジェクトのルートで実行してください');
  }
  final packageName = RegExp(r'^name:\s*(\S+)', multiLine: true)
          .firstMatch(pubspec.readAsStringSync())
          ?.group(1) ??
      'app';

  final created = <String>[];

  void write(String relativePath, String content) {
    final file = File('$projectRoot/$relativePath');
    if (file.existsSync()) return; // 冪等: 上書きしない
    file
      ..createSync(recursive: true)
      ..writeAsStringSync(content);
    created.add(relativePath);
  }

  write('endevir_test/main_test.dart', _mainTestTemplate(packageName));
  write('endevir_test/app_smoke_test.dart', _smokeTestTemplate);
  write('endevir.yaml', _configTemplate);

  // 初期バンドルを生成する（以後は `endevir test` が毎回再生成する）
  writeBundle(enumerateTests('$projectRoot/endevir_test'));
  return created;
}

/// 列挙結果からtest_bundle.g.dartを書き出す（毎回上書き。生成物のため）。
void writeBundle(EnumerationResult enumeration) {
  File('${enumeration.testDir}/test_bundle.g.dart')
      .writeAsStringSync(generateBundle(enumeration));
}

String _mainTestTemplate(String packageName) => '''
import 'package:endevir/endevir.dart';
import 'package:$packageName/main.dart';

import 'test_bundle.g.dart';

Future<void> main() => endevirRunnerMain(
      // endevir_test/*_test.dart のテストは自動で登録されます（生成バンドル経由）
      registerTests: registerAllTests,
      // アプリのルートWidgetに置き換えてください
      appBuilder: () => const MyApp(),
    );
''';

const _smokeTestTemplate = '''
import 'package:endevir/endevir.dart';
import 'package:flutter/material.dart';

void main() {
  endevirTest('アプリが起動する', (e) async {
    // 最初の画面に表示されるテキスト等に置き換えてください
    await e.expectVisible(MaterialApp);
  });
}
''';

const _configTemplate = '''
# Endevir 実行設定。テスト単位のAPI引数はこの既定値を上書きします。
timeoutSeconds: 10 # 待機のデフォルトタイムアウト
stabilityFrames: 3 # タップ前の位置安定判定に必要な連続不変フレーム数
retries: 0 # 失敗テストのリトライ回数
''';

Future<InitResult> initializeProject({
  required String projectRoot,
  required List<String> dependencySpecs,
  required String flutter,
  List<String> flutterPrefix = const [],
  InitProcessRunner processRunner = _runInitProcess,
}) async {
  final transaction = _InitTransaction(projectRoot);
  var created = const <String>[];
  try {
    created = scaffoldProject(projectRoot);
    final result = await processRunner(
      flutter,
      [...flutterPrefix, 'pub', 'add', ...dependencySpecs],
      workingDirectory: projectRoot,
    );
    if (result.exitCode != 0) {
      transaction.rollback();
      return InitResult(
        exitCode: 1,
        created: created,
        rolledBack: true,
        error: '${result.stderr}${result.stdout}'.trim(),
      );
    }
    return InitResult(exitCode: 0, created: created);
  } on ProcessException catch (error) {
    transaction.rollback();
    return InitResult(
      exitCode: 1,
      created: created,
      rolledBack: true,
      error: error.toString(),
    );
  } catch (_) {
    transaction.rollback();
    rethrow;
  }
}

Future<ProcessResult> _runInitProcess(
  String executable,
  List<String> arguments, {
  String? workingDirectory,
}) =>
    Process.run(executable, arguments, workingDirectory: workingDirectory);

Future<int> runInitCommand(List<String> args) async {
  final parser = ArgParser()
    ..addOption('endevir-path',
        help: 'ローカルEndevirモノレポへのパス')
    ..addOption('endevir-git', help: 'EndevirモノレポのGit URL')
    ..addOption('endevir-ref', help: '--endevir-gitで使用するbranch/tag/commit')
    ..addFlag('help', abbr: 'h', negatable: false);
  final options = parser.parse(args);
  if (options['help'] as bool) {
    print('usage: endevir init [--endevir-path <path> | '
        '--endevir-git <url> [--endevir-ref <ref>]]');
    print(parser.usage);
    return 0;
  }

  final EndevirDependencyPlan plan;
  try {
    plan = buildDependencyPlan(
      path: options['endevir-path'] as String?,
      git: options['endevir-git'] as String?,
      ref: options['endevir-ref'] as String?,
    );
  } on ArgumentError catch (error) {
    stderr.writeln('error: ${error.message}');
    return 64;
  }
  if (plan.source == EndevirDependencySource.path) {
    final root = options['endevir-path'] as String;
    if (!Directory(root).existsSync()) {
      stderr.writeln('error: Endevirモノレポが見つかりません: $root');
      return 64;
    }
  }

  print('[endevir] dependency source: ${plan.description}');
  print('[endevir] add dependencies: endevir, endevir_cli');
  final result = await initializeProject(
    projectRoot: Directory.current.path,
    dependencySpecs: plan.specs,
    flutter: flutterExecutable(),
    flutterPrefix: flutterArgPrefix(),
  );
  if (result.exitCode != 0) {
    if (result.error?.isNotEmpty ?? false) stderr.writeln(result.error);
    if (result.rolledBack) {
      stderr.writeln('[endevir] init failed; project changes were rolled back');
    }
    return result.exitCode;
  }

  for (final path in result.created) {
    print('[endevir] created: $path');
  }
  if (result.created.isEmpty) {
    print('[endevir] 雛形は既に存在します（上書きしません）');
  }

  print('');
  print('[endevir] 導入完了。次のコマンドでテストを実行できます:');
  print('  dart run endevir_cli:endevir_cli test -p ios -d <device>');
  return 0;
}
