// `endevir native android`: ネイティブテスト写像（CORE-109、ADR-006）。
//
// 静的マニフェスト（ADR-005）からParameterized JUnitのテストケースを生成し、
// 各ケースがアプリ内エージェントの /runTest（HTTP補助エンドポイント）経由で
// テストを1件ずつ実行する。Firebase Test Lab等のinstrumentation対応
// デバイスファームにそのまま持ち込める形を生成する。
// ignore_for_file: avoid_print
import 'dart:convert';
import 'dart:io';

import 'package:args/args.dart';

import 'enumerate.dart';
import 'flutter_cli.dart';

/// Android instrumentation写像のスキャフォールドを生成・更新する。
/// Kotlin/マニフェスト/assetsは生成物（毎回上書き）、gradleは冪等注入。
void scaffoldAndroidNative(String projectRoot) {
  final gradleFile = File('$projectRoot/android/app/build.gradle.kts');
  if (!gradleFile.existsSync()) {
    throw StateError('android/app/build.gradle.kts が見つかりません');
  }
  final applicationId =
      RegExp(r'applicationId\s*=?\s*"([^"]+)"')
          .firstMatch(gradleFile.readAsStringSync())
          ?.group(1);
  if (applicationId == null) {
    throw StateError('applicationId が build.gradle.kts に見つかりません');
  }

  final androidTestDir = '$projectRoot/android/app/src/androidTest';
  final packagePath = applicationId.replaceAll('.', '/');

  // Kotlinランナー（生成物: 毎回上書き）
  File('$androidTestDir/kotlin/$packagePath/EndevirNativeTest.kt')
    ..createSync(recursive: true)
    ..writeAsStringSync(_kotlinTemplate(applicationId));

  // androidTestマニフェスト（ADR-006の落とし穴3: exported要件の上書き）
  File('$androidTestDir/AndroidManifest.xml')
    ..createSync(recursive: true)
    ..writeAsStringSync(_androidTestManifest);

  // テストマニフェスト（静的列挙の生成物）
  final enumeration = enumerateTests('$projectRoot/endevir_test');
  for (final warning in enumeration.warnings) {
    print('[endevir] WARNING: $warning');
  }
  File('$androidTestDir/assets/endevir_manifest.json')
    ..createSync(recursive: true)
    ..writeAsStringSync(jsonEncode([
      for (final entry in enumeration.entries)
        {'fullName': entry.fullName, 'file': entry.file},
    ]));

  _patchGradle(gradleFile);
}

/// build.gradle.ktsへの冪等注入（runner指定+androidTest依存）。
void _patchGradle(File gradleFile) {
  var content = gradleFile.readAsStringSync();

  if (!content.contains('testInstrumentationRunner')) {
    content = content.replaceFirst(
      RegExp(r'(defaultConfig\s*\{)'),
      '\$1\n        // Endevir: ネイティブテスト写像用ランナー（ADR-006）\n'
      '        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"',
    );
  }

  if (!content.contains('androidx.test:runner')) {
    content += '''

dependencies {
    // Endevir: instrumentationテスト（ネイティブ写像）用。
    // バージョンはFlutterのdebug embeddingが持ち込むandroidx.test:runner 1.2.0
    // に合わせる（AGPのconsistent resolutionとの衝突回避、ADR-006）
    androidTestImplementation("androidx.test.ext:junit:1.1.1")
    androidTestImplementation("androidx.test:runner:1.2.0")
}
''';
  }

  gradleFile.writeAsStringSync(content);
}

String _kotlinTemplate(String applicationId) => '''
// GENERATED by endevir - DO NOT EDIT
// ネイティブテスト写像（ADR-006）: 静的マニフェストからテストケースを生成し、
// アプリ内エージェントの /runTest でDartテストを1件ずつ実行する。
package $applicationId

import androidx.test.platform.app.InstrumentationRegistry
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.Parameterized
import java.io.BufferedReader
import java.net.Socket
import java.net.URLEncoder

@RunWith(Parameterized::class)
class EndevirNativeTest(private val testName: String) {

    companion object {
        private const val AGENT_PORT = 8808

        @JvmStatic
        @Parameterized.Parameters(name = "{0}")
        fun testCases(): List<String> {
            val assets = InstrumentationRegistry.getInstrumentation().context.assets
            val json = assets.open("endevir_manifest.json").bufferedReader().readText()
            val array = JSONArray(json)
            return (0 until array.length()).map { array.getJSONObject(it).getString("fullName") }
        }

        /**
         * エージェントの死活を確認し、落ちていればアプリを起動して待つ。
         * MonitoringInstrumentationは管理外のActivityを終了させることがあるため、
         * テストごとに自己回復できる形にする（ADR-006の落とし穴4）。
         */
        fun ensureAppRunning() {
            if (isAgentAlive()) return
            InstrumentationRegistry.getInstrumentation().uiAutomation
                .executeShellCommand(
                    "am start -n $applicationId/.MainActivity"
                ).close()
            repeat(300) {
                if (isAgentAlive()) return
                Thread.sleep(200)
            }
            error("endevir agent not reachable on port \$AGENT_PORT")
        }

        private fun isAgentAlive(): Boolean = try {
            httpGet("/ping", timeoutMs = 2_000).contains("pong")
        } catch (_: Exception) {
            false
        }

        /** 素のSocketによる最小HTTP GET（cleartextポリシー非依存） */
        fun httpGet(pathWithQuery: String, timeoutMs: Int = 120_000): String {
            Socket("127.0.0.1", AGENT_PORT).use { socket ->
                socket.soTimeout = timeoutMs
                val writer = socket.getOutputStream().bufferedWriter()
                writer.write("GET \$pathWithQuery HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n")
                writer.flush()
                val response = socket.getInputStream()
                    .bufferedReader()
                    .use(BufferedReader::readText)
                // chunked encodingを考慮し、最初の{から最後の}までをJSONとして扱う
                val body = response.substringAfter("\\r\\n\\r\\n")
                return body.substring(body.indexOf('{'), body.lastIndexOf('}') + 1)
            }
        }
    }

    @Test
    fun runDartTest() {
        ensureAppRunning()
        val encoded = URLEncoder.encode(testName, "UTF-8")
        val result = JSONObject(httpGet("/runTest?name=\$encoded"))
        val error = result.optString("error", "")
        assertEquals(
            "Dart test '\$testName' failed\${if (error.isNotEmpty()) ": \$error" else ""}",
            "passed",
            result.getString("status"),
        )
    }
}
''';

const _androidTestManifest = '''
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
    <!-- GENERATED by endevir - DO NOT EDIT
         古いandroidx.test:core（Flutter embeddingの1.2.0系制約に合わせた
         バージョン）のマニフェストがtargetSdk 31+のexported明示要件を
         満たさないため、ここで上書きする（ADR-006の落とし穴3） -->
    <application>
        <activity
            android:name="androidx.test.core.app.InstrumentationActivityInvoker\$BootstrapActivity"
            android:exported="false"
            tools:node="merge" />
        <activity
            android:name="androidx.test.core.app.InstrumentationActivityInvoker\$EmptyActivity"
            android:exported="false"
            tools:node="merge" />
        <activity
            android:name="androidx.test.core.app.InstrumentationActivityInvoker\$EmptyFloatingActivity"
            android:exported="false"
            tools:node="merge" />
    </application>
</manifest>
''';

Future<int> runNativeCommand(List<String> args) async {
  final parser = ArgParser()
    ..addFlag('run', help: 'connectedAndroidTestを実行する')
    ..addFlag('build',
        help: 'デバイスファーム持ち込み用APK（app + androidTest）をビルドする')
    ..addOption('device', abbr: 'd', help: 'adbシリアル（--run時）')
    ..addOption('target',
        abbr: 't', defaultsTo: 'endevir_test/main_test.dart')
    ..addFlag('help', abbr: 'h', negatable: false);
  final options = parser.parse(args);
  if (options['help'] as bool || args.isEmpty || args.first != 'android') {
    print('usage: endevir native android [--run [-d serial]] [-t target]');
    print(parser.usage);
    return args.isEmpty ? 64 : 0;
  }
  final rest = parser.parse(args.skip(1).toList());

  scaffoldAndroidNative(Directory.current.path);
  print('[endevir] android instrumentation scaffold updated');

  if (rest['build'] as bool) {
    return _buildFarmApks(rest['target'] as String);
  }

  if (!(rest['run'] as bool)) {
    print('');
    print('[endevir] 次のステップ:');
    print('  ローカル実行:              endevir native android --run');
    print('  デバイスファーム用APK作成: endevir native android --build');
    return 0;
  }

  // gradle実行用のJDKを解決する（ADR-006の落とし穴1）
  final environment = Map<String, String>.from(Platform.environment);
  final jdk = await _resolveJdk();
  if (jdk != null) {
    environment['JAVA_HOME'] = jdk;
    print('[endevir] JAVA_HOME: $jdk');
  }

  print('[endevir] gradlew connectedDebugAndroidTest');
  final process = await Process.start(
    './gradlew',
    [
      ':app:connectedDebugAndroidTest',
      '-Ptarget=${rest['target'] as String}',
    ],
    workingDirectory: 'android',
    environment: environment,
    mode: ProcessStartMode.inheritStdio,
  );
  return process.exitCode;
}

/// デバイスファーム（Firebase Test Lab等）持ち込み用のAPKをビルドする。
/// app APKは必ずテストエントリポイント（エージェント入り）でビルドする——
/// 素のlib/main.dartビルドを持ち込むと全テストがエージェント接続待ちで失敗する。
Future<int> _buildFarmApks(String target) async {
  print('[endevir] build app APK (target: $target)');
  final flutterProcess = await Process.start(
    flutterExecutable(),
    [...flutterArgPrefix(), 'build', 'apk', '--debug', '-t', target],
    mode: ProcessStartMode.inheritStdio,
  );
  if (await flutterProcess.exitCode != 0) return 1;

  final environment = Map<String, String>.from(Platform.environment);
  final jdk = await _resolveJdk();
  if (jdk != null) environment['JAVA_HOME'] = jdk;

  print('[endevir] build androidTest APK');
  final gradleProcess = await Process.start(
    './gradlew',
    [':app:assembleDebugAndroidTest', '-Ptarget=$target'],
    workingDirectory: 'android',
    environment: environment,
    mode: ProcessStartMode.inheritStdio,
  );
  if (await gradleProcess.exitCode != 0) return 1;

  const appApk = 'build/app/outputs/flutter-apk/app-debug.apk';
  const testApk =
      'build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk';
  print('');
  print('[endevir] APKを生成しました:');
  print('  app:  $appApk');
  print('  test: $testApk');
  print('');
  print('[endevir] Firebase Test Labで実行するには:');
  print('  gcloud firebase test android run \\');
  print('    --type instrumentation \\');
  print('    --app $appApk \\');
  print('    --test $testApk \\');
  print('    --device model=MediumPhone.arm,version=33');
  return 0;
}

/// Gradle/Kotlinと互換のあるJDK（17〜21）を探す。
Future<String?> _resolveJdk() async {
  // 1) 現在のJAVA_HOMEが互換ならそのまま
  final current = Platform.environment['JAVA_HOME'];
  if (current != null && await _isCompatibleJdk('$current/bin/java')) {
    return current;
  }
  // 2) Flutterが設定するjdk-dir
  final config = await Process.run(
      flutterExecutable(), [...flutterArgPrefix(), 'config', '--list']);
  final jdkDir = RegExp(r'jdk-dir:\s*(.+)')
      .firstMatch(config.stdout as String)
      ?.group(1)
      ?.trim();
  if (jdkDir != null &&
      jdkDir != '(Not set)' &&
      await _isCompatibleJdk('$jdkDir/bin/java')) {
    return jdkDir;
  }
  // 3) macOS: java_homeで17を探す
  if (Platform.isMacOS) {
    final result =
        await Process.run('/usr/libexec/java_home', ['-v', '17']);
    if (result.exitCode == 0) {
      return (result.stdout as String).trim();
    }
  }
  print('[endevir] WARNING: 互換JDK（17〜21）が見つかりません。'
      'gradleが失敗する場合はJAVA_HOMEを設定してください');
  return null;
}

Future<bool> _isCompatibleJdk(String javaPath) async {
  try {
    final result = await Process.run(javaPath, ['-version']);
    final major = int.tryParse(
        RegExp(r'version "(\d+)').firstMatch('${result.stderr}')?.group(1) ??
            '');
    return major != null && major >= 17 && major <= 21;
  } on ProcessException {
    return false;
  }
}
