// GENERATED by endevir - DO NOT EDIT
// ネイティブテスト写像（ADR-006）: 静的マニフェストからテストケースを生成し、
// アプリ内エージェントの /runTest でDartテストを1件ずつ実行する。
package dev.endevir.example_app

import androidx.test.platform.app.InstrumentationRegistry
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.Parameterized
import java.io.BufferedReader
import java.net.Socket
import java.net.URLEncoder

@RunWith(Parameterized::class)
class EndevirNativeTest(private val testName: String) {

    companion object {
        private const val AGENT_PORT = 8808

        @JvmStatic
        @Parameterized.Parameters(name = "{0}")
        fun testCases(): List<String> {
            val assets = InstrumentationRegistry.getInstrumentation().context.assets
            val json = assets.open("endevir_manifest.json").bufferedReader().readText()
            val array = JSONArray(json)
            return (0 until array.length()).map { array.getJSONObject(it).getString("fullName") }
        }

        /**
         * エージェントの死活を確認し、落ちていればアプリを起動して待つ。
         * MonitoringInstrumentationは管理外のActivityを終了させることがあるため、
         * テストごとに自己回復できる形にする（ADR-006の落とし穴4）。
         */
        fun ensureAppRunning() {
            if (isAgentAlive()) return
            InstrumentationRegistry.getInstrumentation().uiAutomation
                .executeShellCommand(
                    "am start -n dev.endevir.example_app/.MainActivity"
                ).close()
            repeat(300) {
                if (isAgentAlive()) return
                Thread.sleep(200)
            }
            error("endevir agent not reachable on port $AGENT_PORT")
        }

        private fun isAgentAlive(): Boolean = try {
            httpGet("/ping", timeoutMs = 2_000).contains("pong")
        } catch (_: Exception) {
            false
        }

        /** 素のSocketによる最小HTTP GET（cleartextポリシー非依存） */
        fun httpGet(pathWithQuery: String, timeoutMs: Int = 120_000): String {
            Socket("127.0.0.1", AGENT_PORT).use { socket ->
                socket.soTimeout = timeoutMs
                val writer = socket.getOutputStream().bufferedWriter()
                writer.write("GET $pathWithQuery HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n")
                writer.flush()
                val response = socket.getInputStream()
                    .bufferedReader()
                    .use(BufferedReader::readText)
                // chunked encodingを考慮し、最初の{から最後の}までをJSONとして扱う
                val body = response.substringAfter("\r\n\r\n")
                return body.substring(body.indexOf('{'), body.lastIndexOf('}') + 1)
            }
        }
    }

    @Test
    fun runDartTest() {
        ensureAppRunning()
        val encoded = URLEncoder.encode(testName, "UTF-8")
        val result = JSONObject(httpGet("/runTest?name=$encoded"))
        val error = result.optString("error", "")
        assertEquals(
            "Dart test '$testName' failed${if (error.isNotEmpty()) ": $error" else ""}",
            "passed",
            result.getString("status"),
        )
    }
}
